language: rust
dist: trusty

#services:
#  - docker

install: travis_wait 30

rust:
  - stable

cache: cargo

before_script:
  - rustup component add clippy

script:
  - cargo build
#  - cargo clippy --all-targets
  - cargo test
