language: rust
dist: trusty

#services:
#  - docker

rust:
  - stable

cache: cargo

before_script:
  - rustup component add clippy

script:
  - cargo build
  - cargo clippy --all-targets
  - cargo test
